package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

func main() {
	file, err := os.Open("internal/api/udr.gen.go")
	if err != nil {
		fmt.Printf("Error opening file: %v\n", err)
		os.Exit(1)
	}
	defer file.Close()

	out, err := os.Create("internal/api/stubs.gen.go")
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	out.WriteString("// Code generated by stubgen. DO NOT EDIT.\n")
	out.WriteString("package api\n\n")
	out.WriteString("import (\n")
	out.WriteString("\t\"net/http\"\n")
	out.WriteString(")\n\n")

	scanner := bufio.NewScanner(file)
	inInterface := false
	methodRegex := regexp.MustCompile(`^\s*([A-Za-z0-9_]+)\((.*)\)`)

	for scanner.Scan() {
		line := scanner.Text()
		if strings.Contains(line, "type ServerInterface interface {") {
			inInterface = true
			continue
		}
		if inInterface && strings.HasPrefix(strings.TrimSpace(line), "}") {
			inInterface = false
			break
		}
		if inInterface {
			trimmed := strings.TrimSpace(line)
			if trimmed == "" || strings.HasPrefix(trimmed, "//") {
				continue
			}
			matches := methodRegex.FindStringSubmatch(trimmed)
			if len(matches) > 0 {
				methodName := matches[1]
				args := matches[2]
				// Generate implementation
				impl := fmt.Sprintf("func (s *Server) %s(%s) {\n\ts.Dispatch(w, r, \"%s\")\n}\n\n", methodName, args, methodName)
				out.WriteString(impl)
			}
		}
	}

	if err := scanner.Err(); err != nil {
		fmt.Printf("Error scanning file: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("stubs.gen.go generated successfully.")
}
