// Code generated by stubgen. DO NOT EDIT.
package api

import (
	"net/http"
)

func (s *Server) ReadBdtPolicyData(w http.ResponseWriter, r *http.Request, params ReadBdtPolicyDataParams) {
	s.Dispatch(w, r, "ReadBdtPolicyData")
}

func (s *Server) DeleteIndividualAppliedBdtPolicyData(w http.ResponseWriter, r *http.Request, bdtPolicyId string) {
	s.Dispatch(w, r, "DeleteIndividualAppliedBdtPolicyData")
}

func (s *Server) UpdateIndividualAppliedBdtPolicyData(w http.ResponseWriter, r *http.Request, bdtPolicyId string) {
	s.Dispatch(w, r, "UpdateIndividualAppliedBdtPolicyData")
}

func (s *Server) CreateIndividualAppliedBdtPolicyData(w http.ResponseWriter, r *http.Request, bdtPolicyId string) {
	s.Dispatch(w, r, "CreateIndividualAppliedBdtPolicyData")
}

func (s *Server) ReadInfluenceData(w http.ResponseWriter, r *http.Request, params ReadInfluenceDataParams) {
	s.Dispatch(w, r, "ReadInfluenceData")
}

func (s *Server) ReadInfluenceDataSubscriptions(w http.ResponseWriter, r *http.Request, params ReadInfluenceDataSubscriptionsParams) {
	s.Dispatch(w, r, "ReadInfluenceDataSubscriptions")
}

func (s *Server) CreateIndividualInfluenceDataSubscription(w http.ResponseWriter, r *http.Request) {
	s.Dispatch(w, r, "CreateIndividualInfluenceDataSubscription")
}

func (s *Server) DeleteIndividualInfluenceDataSubscription(w http.ResponseWriter, r *http.Request, subscriptionId string) {
	s.Dispatch(w, r, "DeleteIndividualInfluenceDataSubscription")
}

func (s *Server) ReadIndividualInfluenceDataSubscription(w http.ResponseWriter, r *http.Request, subscriptionId string) {
	s.Dispatch(w, r, "ReadIndividualInfluenceDataSubscription")
}

func (s *Server) ReplaceIndividualInfluenceDataSubscription(w http.ResponseWriter, r *http.Request, subscriptionId string) {
	s.Dispatch(w, r, "ReplaceIndividualInfluenceDataSubscription")
}

func (s *Server) DeleteIndividualInfluenceData(w http.ResponseWriter, r *http.Request, influenceId string) {
	s.Dispatch(w, r, "DeleteIndividualInfluenceData")
}

func (s *Server) UpdateIndividualInfluenceData(w http.ResponseWriter, r *http.Request, influenceId string) {
	s.Dispatch(w, r, "UpdateIndividualInfluenceData")
}

func (s *Server) CreateOrReplaceIndividualInfluenceData(w http.ResponseWriter, r *http.Request, influenceId string) {
	s.Dispatch(w, r, "CreateOrReplaceIndividualInfluenceData")
}

func (s *Server) ReadIPTVCongifurationData(w http.ResponseWriter, r *http.Request, params ReadIPTVCongifurationDataParams) {
	s.Dispatch(w, r, "ReadIPTVCongifurationData")
}

func (s *Server) DeleteIndividualIPTVConfigurationData(w http.ResponseWriter, r *http.Request, configurationId string) {
	s.Dispatch(w, r, "DeleteIndividualIPTVConfigurationData")
}

func (s *Server) PartialReplaceIndividualIPTVConfigurationData(w http.ResponseWriter, r *http.Request, configurationId string) {
	s.Dispatch(w, r, "PartialReplaceIndividualIPTVConfigurationData")
}

func (s *Server) CreateOrReplaceIndividualIPTVConfigurationData(w http.ResponseWriter, r *http.Request, configurationId string) {
	s.Dispatch(w, r, "CreateOrReplaceIndividualIPTVConfigurationData")
}

func (s *Server) ReadPFDData(w http.ResponseWriter, r *http.Request, params ReadPFDDataParams) {
	s.Dispatch(w, r, "ReadPFDData")
}

func (s *Server) DeleteIndividualPFDData(w http.ResponseWriter, r *http.Request, appId string) {
	s.Dispatch(w, r, "DeleteIndividualPFDData")
}

func (s *Server) ReadIndividualPFDData(w http.ResponseWriter, r *http.Request, appId string) {
	s.Dispatch(w, r, "ReadIndividualPFDData")
}

func (s *Server) CreateOrReplaceIndividualPFDData(w http.ResponseWriter, r *http.Request, appId string) {
	s.Dispatch(w, r, "CreateOrReplaceIndividualPFDData")
}

func (s *Server) ReadServiceParameterData(w http.ResponseWriter, r *http.Request, params ReadServiceParameterDataParams) {
	s.Dispatch(w, r, "ReadServiceParameterData")
}

func (s *Server) DeleteIndividualServiceParameterData(w http.ResponseWriter, r *http.Request, serviceParamId string) {
	s.Dispatch(w, r, "DeleteIndividualServiceParameterData")
}

func (s *Server) UpdateIndividualServiceParameterData(w http.ResponseWriter, r *http.Request, serviceParamId string) {
	s.Dispatch(w, r, "UpdateIndividualServiceParameterData")
}

func (s *Server) CreateOrReplaceServiceParameterData(w http.ResponseWriter, r *http.Request, serviceParamId string) {
	s.Dispatch(w, r, "CreateOrReplaceServiceParameterData")
}

func (s *Server) ReadApplicationDataChangeSubscriptions(w http.ResponseWriter, r *http.Request, params ReadApplicationDataChangeSubscriptionsParams) {
	s.Dispatch(w, r, "ReadApplicationDataChangeSubscriptions")
}

func (s *Server) CreateIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request) {
	s.Dispatch(w, r, "CreateIndividualApplicationDataSubscription")
}

func (s *Server) DeleteIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "DeleteIndividualApplicationDataSubscription")
}

func (s *Server) ReadIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "ReadIndividualApplicationDataSubscription")
}

func (s *Server) ReplaceIndividualApplicationDataSubscription(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "ReplaceIndividualApplicationDataSubscription")
}

func (s *Server) CreateIndividualExposureDataSubscription(w http.ResponseWriter, r *http.Request) {
	s.Dispatch(w, r, "CreateIndividualExposureDataSubscription")
}

func (s *Server) DeleteIndividualExposureDataSubscription(w http.ResponseWriter, r *http.Request, subId string) {
	s.Dispatch(w, r, "DeleteIndividualExposureDataSubscription")
}

func (s *Server) ReplaceIndividualExposureDataSubscription(w http.ResponseWriter, r *http.Request, subId string) {
	s.Dispatch(w, r, "ReplaceIndividualExposureDataSubscription")
}

func (s *Server) DeleteAccessAndMobilityData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "DeleteAccessAndMobilityData")
}

func (s *Server) QueryAccessAndMobilityData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryAccessAndMobilityDataParams) {
	s.Dispatch(w, r, "QueryAccessAndMobilityData")
}

func (s *Server) UpdateAccessAndMobilityData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "UpdateAccessAndMobilityData")
}

func (s *Server) CreateOrReplaceAccessAndMobilityData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateOrReplaceAccessAndMobilityData")
}

func (s *Server) DeleteSessionManagementData(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId) {
	s.Dispatch(w, r, "DeleteSessionManagementData")
}

func (s *Server) QuerySessionManagementData(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId, params QuerySessionManagementDataParams) {
	s.Dispatch(w, r, "QuerySessionManagementData")
}

func (s *Server) CreateOrReplaceSessionManagementData(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId) {
	s.Dispatch(w, r, "CreateOrReplaceSessionManagementData")
}

func (s *Server) ReadBdtData(w http.ResponseWriter, r *http.Request, params ReadBdtDataParams) {
	s.Dispatch(w, r, "ReadBdtData")
}

func (s *Server) DeleteIndividualBdtData(w http.ResponseWriter, r *http.Request, bdtReferenceId string) {
	s.Dispatch(w, r, "DeleteIndividualBdtData")
}

func (s *Server) ReadIndividualBdtData(w http.ResponseWriter, r *http.Request, bdtReferenceId string, params ReadIndividualBdtDataParams) {
	s.Dispatch(w, r, "ReadIndividualBdtData")
}

func (s *Server) UpdateIndividualBdtData(w http.ResponseWriter, r *http.Request, bdtReferenceId string) {
	s.Dispatch(w, r, "UpdateIndividualBdtData")
}

func (s *Server) CreateIndividualBdtData(w http.ResponseWriter, r *http.Request, bdtReferenceId string) {
	s.Dispatch(w, r, "CreateIndividualBdtData")
}

func (s *Server) ReadPlmnUePolicySet(w http.ResponseWriter, r *http.Request, plmnId VarPlmnId) {
	s.Dispatch(w, r, "ReadPlmnUePolicySet")
}

func (s *Server) ReadSponsorConnectivityData(w http.ResponseWriter, r *http.Request, sponsorId string) {
	s.Dispatch(w, r, "ReadSponsorConnectivityData")
}

func (s *Server) CreateIndividualPolicyDataSubscription(w http.ResponseWriter, r *http.Request) {
	s.Dispatch(w, r, "CreateIndividualPolicyDataSubscription")
}

func (s *Server) DeleteIndividualPolicyDataSubscription(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "DeleteIndividualPolicyDataSubscription")
}

func (s *Server) ReplaceIndividualPolicyDataSubscription(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "ReplaceIndividualPolicyDataSubscription")
}

func (s *Server) ReadAccessAndMobilityPolicyData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "ReadAccessAndMobilityPolicyData")
}

func (s *Server) ReadOperatorSpecificData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params ReadOperatorSpecificDataParams) {
	s.Dispatch(w, r, "ReadOperatorSpecificData")
}

func (s *Server) UpdateOperatorSpecificData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "UpdateOperatorSpecificData")
}

func (s *Server) ReplaceOperatorSpecificData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "ReplaceOperatorSpecificData")
}

func (s *Server) ReadSessionManagementPolicyData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params ReadSessionManagementPolicyDataParams) {
	s.Dispatch(w, r, "ReadSessionManagementPolicyData")
}

func (s *Server) UpdateSessionManagementPolicyData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "UpdateSessionManagementPolicyData")
}

func (s *Server) DeleteUsageMonitoringInformation(w http.ResponseWriter, r *http.Request, ueId VarUeId, usageMonId string) {
	s.Dispatch(w, r, "DeleteUsageMonitoringInformation")
}

func (s *Server) ReadUsageMonitoringInformation(w http.ResponseWriter, r *http.Request, ueId VarUeId, usageMonId string, params ReadUsageMonitoringInformationParams) {
	s.Dispatch(w, r, "ReadUsageMonitoringInformation")
}

func (s *Server) CreateUsageMonitoringResource(w http.ResponseWriter, r *http.Request, ueId VarUeId, usageMonId string) {
	s.Dispatch(w, r, "CreateUsageMonitoringResource")
}

func (s *Server) ReadUEPolicySet(w http.ResponseWriter, r *http.Request, ueId VarUeId, params ReadUEPolicySetParams) {
	s.Dispatch(w, r, "ReadUEPolicySet")
}

func (s *Server) UpdateUEPolicySet(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "UpdateUEPolicySet")
}

func (s *Server) CreateOrReplaceUEPolicySet(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateOrReplaceUEPolicySet")
}

func (s *Server) Query5GVnGroup(w http.ResponseWriter, r *http.Request, params Query5GVnGroupParams) {
	s.Dispatch(w, r, "Query5GVnGroup")
}

func (s *Server) Query5GVnGroupInternal(w http.ResponseWriter, r *http.Request, params Query5GVnGroupInternalParams) {
	s.Dispatch(w, r, "Query5GVnGroupInternal")
}

func (s *Server) Query5GVNGroupPPData(w http.ResponseWriter, r *http.Request, params Query5GVNGroupPPDataParams) {
	s.Dispatch(w, r, "Query5GVNGroupPPData")
}

func (s *Server) Delete5GVnGroup(w http.ResponseWriter, r *http.Request, externalGroupId ExtGroupId) {
	s.Dispatch(w, r, "Delete5GVnGroup")
}

func (s *Server) Get5GVnGroupConfiguration(w http.ResponseWriter, r *http.Request, externalGroupId ExtGroupId) {
	s.Dispatch(w, r, "Get5GVnGroupConfiguration")
}

func (s *Server) Modify5GVnGroup(w http.ResponseWriter, r *http.Request, externalGroupId ExtGroupId, params Modify5GVnGroupParams) {
	s.Dispatch(w, r, "Modify5GVnGroup")
}

func (s *Server) Create5GVnGroup(w http.ResponseWriter, r *http.Request, externalGroupId ExtGroupId) {
	s.Dispatch(w, r, "Create5GVnGroup")
}

func (s *Server) GetGroupIdentifiers(w http.ResponseWriter, r *http.Request, params GetGroupIdentifiersParams) {
	s.Dispatch(w, r, "GetGroupIdentifiers")
}

func (s *Server) QueryGroupEEData(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, params QueryGroupEEDataParams) {
	s.Dispatch(w, r, "QueryGroupEEData")
}

func (s *Server) QueryEeGroupSubscriptions(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, params QueryEeGroupSubscriptionsParams) {
	s.Dispatch(w, r, "QueryEeGroupSubscriptions")
}

func (s *Server) CreateEeGroupSubscriptions(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId) {
	s.Dispatch(w, r, "CreateEeGroupSubscriptions")
}

func (s *Server) RemoveEeGroupSubscriptions(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, subsId string) {
	s.Dispatch(w, r, "RemoveEeGroupSubscriptions")
}

func (s *Server) QueryEeGroupSubscription(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, subsId string) {
	s.Dispatch(w, r, "QueryEeGroupSubscription")
}

func (s *Server) ModifyEeGroupSubscription(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, subsId string, params ModifyEeGroupSubscriptionParams) {
	s.Dispatch(w, r, "ModifyEeGroupSubscription")
}

func (s *Server) UpdateEeGroupSubscriptions(w http.ResponseWriter, r *http.Request, ueGroupId VarUeGroupId, subsId string) {
	s.Dispatch(w, r, "UpdateEeGroupSubscriptions")
}

func (s *Server) GetSharedData(w http.ResponseWriter, r *http.Request, params GetSharedDataParams) {
	s.Dispatch(w, r, "GetSharedData")
}

func (s *Server) GetIndividualSharedData(w http.ResponseWriter, r *http.Request, sharedDataId SharedDataId, params GetIndividualSharedDataParams) {
	s.Dispatch(w, r, "GetIndividualSharedData")
}

func (s *Server) RemoveMultipleSubscriptionDataSubscriptions(w http.ResponseWriter, r *http.Request, params RemoveMultipleSubscriptionDataSubscriptionsParams) {
	s.Dispatch(w, r, "RemoveMultipleSubscriptionDataSubscriptions")
}

func (s *Server) QuerySubsToNotify(w http.ResponseWriter, r *http.Request, params QuerySubsToNotifyParams) {
	s.Dispatch(w, r, "QuerySubsToNotify")
}

func (s *Server) SubscriptionDataSubscriptions(w http.ResponseWriter, r *http.Request) {
	s.Dispatch(w, r, "SubscriptionDataSubscriptions")
}

func (s *Server) RemovesubscriptionDataSubscriptions(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "RemovesubscriptionDataSubscriptions")
}

func (s *Server) QuerySubscriptionDataSubscriptions(w http.ResponseWriter, r *http.Request, subsId string) {
	s.Dispatch(w, r, "QuerySubscriptionDataSubscriptions")
}

func (s *Server) ModifysubscriptionDataSubscription(w http.ResponseWriter, r *http.Request, subsId string, params ModifysubscriptionDataSubscriptionParams) {
	s.Dispatch(w, r, "ModifysubscriptionDataSubscription")
}

func (s *Server) DeleteAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi) {
	s.Dispatch(w, r, "DeleteAuthenticationStatus")
}

func (s *Server) QueryAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryAuthenticationStatusParams) {
	s.Dispatch(w, r, "QueryAuthenticationStatus")
}

func (s *Server) CreateAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi) {
	s.Dispatch(w, r, "CreateAuthenticationStatus")
}

func (s *Server) DeleteIndividualAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi, servingNetworkName ServingNetworkName) {
	s.Dispatch(w, r, "DeleteIndividualAuthenticationStatus")
}

func (s *Server) QueryIndividualAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi, servingNetworkName ServingNetworkName, params QueryIndividualAuthenticationStatusParams) {
	s.Dispatch(w, r, "QueryIndividualAuthenticationStatus")
}

func (s *Server) CreateIndividualAuthenticationStatus(w http.ResponseWriter, r *http.Request, ueId Supi, servingNetworkName ServingNetworkName) {
	s.Dispatch(w, r, "CreateIndividualAuthenticationStatus")
}

func (s *Server) QueryAuthSubsData(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryAuthSubsDataParams) {
	s.Dispatch(w, r, "QueryAuthSubsData")
}

func (s *Server) ModifyAuthenticationSubscription(w http.ResponseWriter, r *http.Request, ueId Supi, params ModifyAuthenticationSubscriptionParams) {
	s.Dispatch(w, r, "ModifyAuthenticationSubscription")
}

func (s *Server) QueryContextData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryContextDataParams) {
	s.Dispatch(w, r, "QueryContextData")
}

func (s *Server) QueryAmfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryAmfContext3gppParams) {
	s.Dispatch(w, r, "QueryAmfContext3gpp")
}

func (s *Server) AmfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params AmfContext3gppParams) {
	s.Dispatch(w, r, "AmfContext3gpp")
}

func (s *Server) CreateAmfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateAmfContext3gpp")
}

func (s *Server) QueryAmfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryAmfContextNon3gppParams) {
	s.Dispatch(w, r, "QueryAmfContextNon3gpp")
}

func (s *Server) AmfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params AmfContextNon3gppParams) {
	s.Dispatch(w, r, "AmfContextNon3gpp")
}

func (s *Server) CreateAmfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateAmfContextNon3gpp")
}

func (s *Server) Queryeesubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryeesubscriptionsParams) {
	s.Dispatch(w, r, "Queryeesubscriptions")
}

func (s *Server) CreateEeSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateEeSubscriptions")
}

func (s *Server) RemoveeeSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemoveeeSubscriptions")
}

func (s *Server) QueryeeSubscription(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "QueryeeSubscription")
}

func (s *Server) ModifyEesubscription(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifyEesubscriptionParams) {
	s.Dispatch(w, r, "ModifyEesubscription")
}

func (s *Server) UpdateEesubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "UpdateEesubscriptions")
}

func (s *Server) RemoveAmfSubscriptionsInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemoveAmfSubscriptionsInfo")
}

func (s *Server) GetAmfSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "GetAmfSubscriptionInfo")
}

func (s *Server) ModifyAmfSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifyAmfSubscriptionInfoParams) {
	s.Dispatch(w, r, "ModifyAmfSubscriptionInfo")
}

func (s *Server) CreateAMFSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "CreateAMFSubscriptions")
}

func (s *Server) RemoveHssSubscriptionsInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemoveHssSubscriptionsInfo")
}

func (s *Server) GetHssSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "GetHssSubscriptionInfo")
}

func (s *Server) ModifyHssSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifyHssSubscriptionInfoParams) {
	s.Dispatch(w, r, "ModifyHssSubscriptionInfo")
}

func (s *Server) CreateHSSSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "CreateHSSSubscriptions")
}

func (s *Server) RemoveSmfSubscriptionsInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemoveSmfSubscriptionsInfo")
}

func (s *Server) GetSmfSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "GetSmfSubscriptionInfo")
}

func (s *Server) ModifySmfSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifySmfSubscriptionInfoParams) {
	s.Dispatch(w, r, "ModifySmfSubscriptionInfo")
}

func (s *Server) CreateSMFSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "CreateSMFSubscriptions")
}

func (s *Server) DeleteIpSmGwContext(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "DeleteIpSmGwContext")
}

func (s *Server) QueryIpSmGwContext(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryIpSmGwContextParams) {
	s.Dispatch(w, r, "QueryIpSmGwContext")
}

func (s *Server) ModifyIpSmGwContext(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "ModifyIpSmGwContext")
}

func (s *Server) CreateIpSmGwContext(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateIpSmGwContext")
}

func (s *Server) QueryUeLocation(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryUeLocationParams) {
	s.Dispatch(w, r, "QueryUeLocation")
}

func (s *Server) DeleteMessageWaitingData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "DeleteMessageWaitingData")
}

func (s *Server) QueryMessageWaitingData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryMessageWaitingDataParams) {
	s.Dispatch(w, r, "QueryMessageWaitingData")
}

func (s *Server) ModifyMessageWaitingData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "ModifyMessageWaitingData")
}

func (s *Server) CreateMessageWaitingData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateMessageWaitingData")
}

func (s *Server) Querysdmsubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QuerysdmsubscriptionsParams) {
	s.Dispatch(w, r, "Querysdmsubscriptions")
}

func (s *Server) CreateSdmSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateSdmSubscriptions")
}

func (s *Server) RemovesdmSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemovesdmSubscriptions")
}

func (s *Server) QuerysdmSubscription(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "QuerysdmSubscription")
}

func (s *Server) ModifysdmSubscription(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifysdmSubscriptionParams) {
	s.Dispatch(w, r, "ModifysdmSubscription")
}

func (s *Server) Updatesdmsubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "Updatesdmsubscriptions")
}

func (s *Server) RemoveHssSDMSubscriptionsInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "RemoveHssSDMSubscriptionsInfo")
}

func (s *Server) GetHssSDMSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "GetHssSDMSubscriptionInfo")
}

func (s *Server) ModifyHssSDMSubscriptionInfo(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string, params ModifyHssSDMSubscriptionInfoParams) {
	s.Dispatch(w, r, "ModifyHssSDMSubscriptionInfo")
}

func (s *Server) CreateHSSSDMSubscriptions(w http.ResponseWriter, r *http.Request, ueId VarUeId, subsId string) {
	s.Dispatch(w, r, "CreateHSSSDMSubscriptions")
}

func (s *Server) QuerySmfRegList(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QuerySmfRegListParams) {
	s.Dispatch(w, r, "QuerySmfRegList")
}

func (s *Server) DeleteSmfRegistration(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId) {
	s.Dispatch(w, r, "DeleteSmfRegistration")
}

func (s *Server) QuerySmfRegistration(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId, params QuerySmfRegistrationParams) {
	s.Dispatch(w, r, "QuerySmfRegistration")
}

func (s *Server) CreateOrUpdateSmfRegistration(w http.ResponseWriter, r *http.Request, ueId VarUeId, pduSessionId PduSessionId) {
	s.Dispatch(w, r, "CreateOrUpdateSmfRegistration")
}

func (s *Server) DeleteSmsfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "DeleteSmsfContext3gpp")
}

func (s *Server) QuerySmsfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QuerySmsfContext3gppParams) {
	s.Dispatch(w, r, "QuerySmsfContext3gpp")
}

func (s *Server) CreateSmsfContext3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateSmsfContext3gpp")
}

func (s *Server) DeleteSmsfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "DeleteSmsfContextNon3gpp")
}

func (s *Server) QuerySmsfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QuerySmsfContextNon3gppParams) {
	s.Dispatch(w, r, "QuerySmsfContextNon3gpp")
}

func (s *Server) CreateSmsfContextNon3gpp(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "CreateSmsfContextNon3gpp")
}

func (s *Server) QueryCoverageRestrictionData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryCoverageRestrictionDataParams) {
	s.Dispatch(w, r, "QueryCoverageRestrictionData")
}

func (s *Server) QueryEEData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryEEDataParams) {
	s.Dispatch(w, r, "QueryEEData")
}

func (s *Server) GetIdentityData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params GetIdentityDataParams) {
	s.Dispatch(w, r, "GetIdentityData")
}

func (s *Server) QueryLcsMoData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryLcsMoDataParams) {
	s.Dispatch(w, r, "QueryLcsMoData")
}

func (s *Server) QueryLcsPrivacyData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryLcsPrivacyDataParams) {
	s.Dispatch(w, r, "QueryLcsPrivacyData")
}

func (s *Server) GetNiddAuData(w http.ResponseWriter, r *http.Request, ueId string, params GetNiddAuDataParams) {
	s.Dispatch(w, r, "GetNiddAuData")
}

func (s *Server) GetOdbData(w http.ResponseWriter, r *http.Request, ueId VarUeId) {
	s.Dispatch(w, r, "GetOdbData")
}

func (s *Server) QueryOperSpecData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryOperSpecDataParams) {
	s.Dispatch(w, r, "QueryOperSpecData")
}

func (s *Server) ModifyOperSpecData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params ModifyOperSpecDataParams) {
	s.Dispatch(w, r, "ModifyOperSpecData")
}

func (s *Server) GetppData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params GetppDataParams) {
	s.Dispatch(w, r, "GetppData")
}

func (s *Server) ModifyPpData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params ModifyPpDataParams) {
	s.Dispatch(w, r, "ModifyPpData")
}

func (s *Server) QueryPPData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryPPDataParams) {
	s.Dispatch(w, r, "QueryPPData")
}

func (s *Server) QueryAuthSoR(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryAuthSoRParams) {
	s.Dispatch(w, r, "QueryAuthSoR")
}

func (s *Server) CreateAuthenticationSoR(w http.ResponseWriter, r *http.Request, ueId Supi, params CreateAuthenticationSoRParams) {
	s.Dispatch(w, r, "CreateAuthenticationSoR")
}

func (s *Server) QueryCagAck(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryCagAckParams) {
	s.Dispatch(w, r, "QueryCagAck")
}

func (s *Server) CreateCagUpdateAck(w http.ResponseWriter, r *http.Request, ueId Supi, params CreateCagUpdateAckParams) {
	s.Dispatch(w, r, "CreateCagUpdateAck")
}

func (s *Server) QueryNssaiAck(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryNssaiAckParams) {
	s.Dispatch(w, r, "QueryNssaiAck")
}

func (s *Server) CreateOrUpdateNssaiAck(w http.ResponseWriter, r *http.Request, ueId Supi, params CreateOrUpdateNssaiAckParams) {
	s.Dispatch(w, r, "CreateOrUpdateNssaiAck")
}

func (s *Server) QueryAuthUPU(w http.ResponseWriter, r *http.Request, ueId Supi, params QueryAuthUPUParams) {
	s.Dispatch(w, r, "QueryAuthUPU")
}

func (s *Server) CreateAuthenticationUPU(w http.ResponseWriter, r *http.Request, ueId Supi, params CreateAuthenticationUPUParams) {
	s.Dispatch(w, r, "CreateAuthenticationUPU")
}

func (s *Server) QueryV2xData(w http.ResponseWriter, r *http.Request, ueId VarUeId, params QueryV2xDataParams) {
	s.Dispatch(w, r, "QueryV2xData")
}

func (s *Server) QueryProvisionedData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QueryProvisionedDataParams) {
	s.Dispatch(w, r, "QueryProvisionedData")
}

func (s *Server) QueryAmData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QueryAmDataParams) {
	s.Dispatch(w, r, "QueryAmData")
}

func (s *Server) QueryLcsBcaData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QueryLcsBcaDataParams) {
	s.Dispatch(w, r, "QueryLcsBcaData")
}

func (s *Server) QuerySmData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QuerySmDataParams) {
	s.Dispatch(w, r, "QuerySmData")
}

func (s *Server) QuerySmfSelectData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QuerySmfSelectDataParams) {
	s.Dispatch(w, r, "QuerySmfSelectData")
}

func (s *Server) QuerySmsData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QuerySmsDataParams) {
	s.Dispatch(w, r, "QuerySmsData")
}

func (s *Server) QuerySmsMngData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QuerySmsMngDataParams) {
	s.Dispatch(w, r, "QuerySmsMngData")
}

func (s *Server) QueryTraceData(w http.ResponseWriter, r *http.Request, ueId VarUeId, servingPlmnId VarPlmnId, params QueryTraceDataParams) {
	s.Dispatch(w, r, "QueryTraceData")
}

